### ISSUE TITLE
Querying channel by `handle`: `id` is `null`

### ISSUE THREAD

**Issue by danielbuechele** [Benjamin-Loison/YouTube-operational-API#127]
Trying to query a channel by its handle using: https://yt.lemnoslife.com/channels?handle=@amelie23karat

The response seems to find the channel, but the `id` is `null.

```json
{ "kind": "youtube#channelListResponse", "etag": "NotImplemented", "items": [ { "kind": "youtube#channel", "etag": "NotImplemented", "id": null } ] }
```

**Comment by danielbuechele** [comment]
Interestingly on yt1.lemnoslife.com and yt2 it works. What's the current recommendation, should I rather use these instances?

**Comment by Benjamin-Loison** [comment]
I am right now testing some load balancing, sorry for the disruption of service.
I'll answer you ASAP.

**Comment by Benjamin-Loison** [comment]
Your issue dates from before [the addition of the load balancer](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/11#issuecomment-1406178638).

In fact your request to https://yt.lemnoslife.com/channels?handle=@amelie23karat was processed by `yt0.lemnoslife.com` which was containing an error, that I solved, in the code for doing load balancing at the PHP level, as `yt0.lemnoslife.com` was detected as sending unusual traffic to YouTube servers (cf #11).

Your problem is now solved, if you still have questions don't hesitate to reopen this issue.

**Comment by Benjamin-Loison** [comment]
So to make it clear the recommendation is to use https://yt.lemnoslife.com, as it's doing load balancing on its own (and as sketched in #11, I may make this load balancer clever such that any load balancer that you would do locally _should in theory be less effecient_ as mine).

Sorry for the disruption of service, it was the first time that I was implementing a load balancer both at code and DNS level (the latter was more complicated due to HTTPS certificates), but now I am comfortable with load balancing.

**Comment by Benjamin-Loison** [comment]
By the way thanks for your input, I may haven't seen the code error otherwise.
