### ISSUE TITLE
Community posts

### ISSUE THREAD

**Issue by God-damnit-all** [Benjamin-Loison/YouTube-operational-API#16]
There's not currently any easy way to retrieve Community posts without using an API key, will you look into adding the retrieval of the Community section into your operational API?

**Comment by Benjamin-Loison** [comment]
AFAIK there isn't any way to retrieve Community posts without using an API key, [except maybe comments](https://developers.google.com/youtube/v3/docs/commentThreads/list#allThreadsRelatedToChannelId).

I am in favor of integrating community posts in my API however as I don't have any YouTube channel with more than 1,000 subscribers, I am not able to try the community tab with write access in order to know the different kind of post there can be (as I remember they can be multiple).

Do you have you such a YouTube account ? Or do you know a YouTube channel that uses all kinds of posts ?

**Comment by Benjamin-Loison** [comment]
By the way [this StackOverflow answer](https://stackoverflow.com/a/72235812/7123660) isn't enough for you ?

If you were able to add a community endpoint to the YouTube operational API, it would be greatly appreciated!

**Comment by Benjamin-Loison** [comment]
> It's indeed possible

May you clarify what do you designate by "It" ?

Anyway we are obliged to use continuation tokens at least internally as YouTube UI uses them.

If you don't have other remarks, what is the continuity of this issue according to you ?
1. you use the StackOverflow method on your own and close this issue
2. you make a Pull Request introducing a `community.php` endpoint by trying to be exhaustive by using a YouTube channel such as the one you mentioned
