### ISSUE TITLE
https://yt.lemnoslife.com/noKey/ gives HTTP 500 error after few requests

### ISSUE THREAD

**Issue by grray** [Benjamin-Loison/YouTube-operational-API#206]
https://yt.lemnoslife.com/noKey/ gives HTTP 500 error after like 10 simple requests, like /playlists. If you retry request, it will allow another 10 requests. It started recently, previously all was fine. 500 request takes 15 or more seconds, looks like timeout.

**Comment by Benjamin-Loison** [comment]
As you mentioned there may be delay in responses due to official instances being overloaded, I just added again another VPS to continue experimenting dealing with so many requests but as it's a free service I can't guarantee any service.

Maybe describe your needs in terms of retrieved data to propose YouTube webscraping alternatives (cf #91).

**Comment by grray** [comment]
Ok, now it works fine, without 500 errors. 

It's not like I'm complaining about the service, it's more like 500 error doesn't give much details, so I'm not sure should I report it or not. It's upstream youtube error, or some internal error, maybe some timeout needs to be increased.

Anyways, now all is fine.

**Comment by Benjamin-Loison** [comment]
Thanks for reporting and precising your intention, I think it's some internal error, as to the best of my knowledge there is no YouTube HTTP error code transmission. However, I was in a hurry and not able to reproduce the issue and as the configurations of apache2 and the Ubuntu 22 server are the default ones, I don't see anything to investigate here, please reopen the issue if it happens again.

**Comment by Benjamin-Loison** [comment]
[As someone reported this issue again on Discord](https://discord.com/channels/933841502155706418/933841503103627316/1159202303149097011), here is a quick update: since about 24 hours [the machine I mentioned](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/206#issuecomment-1730499543) having been added used as an end-server isn't working anymore, so I removed it as an end-server so the official instance is now consisting of a single VPS which is a very fragile setup. I'll add a comment to this issue once the other VPS is stable again and added as an end-server, I'm a bit in a hurry and so it may take a few days.

**Comment by Benjamin-Loison** [comment]
The machine seems to be fixed, I'll let you know if I notice that it's not the case. As a result I added back this end-server to the load balancing, if you encounter again this HTTP 500 error please reopen this issue.

**Comment by Benjamin-Loison** [comment]
[According to the Discord user the issue is still happening](https://discord.com/channels/933841502155706418/933841503103627316/1161334819645571122) but as detailed I'm not able to reproduce the issue and he or anybody else hasn't yet provided a similar shell debugging as I have shared.
