### ISSUE TITLE
"short": { "available": true } appears for all videos

### ISSUE THREAD

**Issue by keshavkaushal** [Benjamin-Loison/YouTube-operational-API#26]
Hi Benjamin,

I have been using the endpoint described in your [Stackoverflow answer](https://stackoverflow.com/a/71194751) in response to a question about determining whether a YouTube video is a Short. In summary, I would check for the following in the response:

**"short": { "available": true }**

If this part is present, the video is a short.

Recently, this has stopped working as expected. All responses now contain this part, even when they are not a short. Example:

This video is not a short: https://www.youtube.com/watch?v=AoDYIz3tNQM
Using this API call: https://yt.lemnoslife.com/videos?part=short&id=AoDYIz3tNQM

I see the following in the response:

**"short": { "available": true }**

**Comment by Benjamin-Loison** [comment]
I am able to reproduce the issue, I am going to investigate this one.

**Comment by Benjamin-Loison** [comment]
@keshavkaushal
The issue is related to #11. It's due to YouTube servers detecting the official instance as sending unusual traffic.
[Hosting you own instance](https://github.com/Benjamin-Loison/YouTube-operational-API#install-your-own-instance-of-the-api) solve the problem.
However the API shouldn't return incorrect result but instead an error message. I am going to work on that.

**Comment by keshavkaushal** [comment]
Thanks for the investigation - I will take a look at self-hosting.

**Comment by Benjamin-Loison** [comment]
I confirm the error message to be added to https://yt.lemnoslife.com/videos?part=short&id=AoDYIz3tNQM
Let me know if you still have problems.
If you need help, don't hesitate to come on [our communication plateforms](https://github.com/Benjamin-Loison/YouTube-operational-API#contact).
