### ISSUE TITLE
Multiple `playlistId` on `/playlistItems` route

### ISSUE THREAD

**Issue by Aynh** [Benjamin-Loison/YouTube-operational-API#6]
Would be nice to fetch multiple playlists at once, they can be placed on the same array if they are sorted by `snippet/publishedAt`.

**Comment by Benjamin-Loison** [comment]
Hello @Aynh, (you're the first person opening an issue on one of my GitHub repository IIRC 🎉).

I think returning a single array merging videos of the different playlists and ordering it using `snippet/publishedAt` is a bit too much specific. However being able to request multiple playlists at once makes sense, but the problem here is that a playlist requires pagination using the `pageToken` URL variable which is directly linked to how the YouTube UI (which we rely on) works, so we can't get rid of it.

So applying your suggestion for multiple playlists would work but we couldn't use pagination (so just retrieve the first videos of the playlists). Would this interest you ? So there wouldn't have pagination (so just having first videos of each playlist) and the URL would be like `playlistItems?part=snippet&playlist=PLAYLIST_ID_0,PLAYLIST_ID_1`.

Otherwise we should add as many `pageToken` as `playlist` so having an URL like `playlistItems?part=snippet&playlist=PLAYLIST_ID_0,PLAYLIST_ID_1&pageToken=PAGE_TOKEN_0,PAGE_TOKEN_1`.

What's your opinion in the light of these arguments ?

**Comment by Aynh** [comment]
Now that I think about it, it may be better to match the response with other multiple-able route (like `/channels` and `/videos`), so no need to merge them. But still, the `pageToken` thing will be complicated for both end-user and the server itself.

Anyways, I was planning to use Youtube Data API as some sort of subscription feed, basically the result will be like [Youtube subscription page](https://www.youtube.com/feed/subscriptions) in JSON format (like `/playlistItems` route response to be exact). But the thing is, I'm using [Cloudflare Workers](https://developers.cloudflare.com/workers/) and there is this _cruel_ [`subrequest`](https://developers.cloudflare.com/workers/platform/limits/#subrequests) limit of 50, so fetching the channel's upload playlists one by one is not an option as I will hit the limit sooner or later if I were to fetch many channels.

I think this kind of _feature_ should implemented be on as separate route (maybe `/feed`?) with (multiple) `channelId` as search parameters, there is no need to use `pageToken` here because most of the time only the latest feeds are meant to be consumed (like RSS).

I'd love to open a PR on this _`/feed` route_, but I never learned PHP so I'm not really sure.

**Comment by Benjamin-Loison** [comment]
Since I haven't been overly exploited yet, I'm willing to take on the PR.

After reading your answer it seems that the following solution would fit your needs as `uploads` playlist firstly show the more recent videos.

> So applying your suggestion for multiple playlists would work but we couldn't use pagination (so just retrieve the first videos of the playlists). Would this interest you ? So there wouldn't have pagination (so just having first videos of each playlist) and the URL would be like playlistItems?part=snippet&playlist=PLAYLIST_ID_0,PLAYLIST_ID_1,...,PLAYLIST_ID_N.

[Source](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/6#issuecomment-1176651409)

Wouldn't [Subscribing to Push Notifications](https://developers.google.com/youtube/v3/guides/push_notifications) fit your needs in an easier way ?

**Comment by Aynh** [comment]
Wow didn't know that, guess I need to read more docs...

That seems to be a good solution, but it doesn't really fit my needs since the `subscription` is not really customizable there. That is a problem because I use the `subscription` of my channel to get my subscriptions list.

**Comment by BenjaminLoison** [comment]
> but it doesn't really fit my needs since the subscription is not really customizable there

What you can do is: looping over your subscriptions by using [Subscriptions: list](https://developers.google.com/youtube/v3/docs/subscriptions/list) and [Subscribe to Push Notifications](https://developers.google.com/youtube/v3/guides/push_notifications) for each channel.

Why wouldn't it be enough "really customizable" ?

**Comment by Benjamin-Loison** [comment]
> but it doesn't really fit my needs since the subscription is not really customizable there

What you can do is: looping over your subscriptions by using [Subscriptions: list](https://developers.google.com/youtube/v3/docs/subscriptions/list) and [Subscribe to Push Notifications](https://developers.google.com/youtube/v3/guides/push_notifications) for each channel.

Why wouldn't it be enough "really customizable" ?

**Comment by Aynh** [comment]
Sorry, I think I picked the wrong word there. What I meant was something like "it's not really dynamic", I don't want to redo the step over and over even when I `subscribe` or `unsubscribe`.

> What you can do is: looping over your subscriptions by using Subscriptions: list and Subscribe to Push Notifications for each channel.

Yes it's possible to subscribe and unsubscribe to `push notifications` using [HTTP requests](https://pubsubhubbub.github.io/PubSubHubbub/pubsubhubbub-core-0.4.html#rfc.section.5.1). But then I have to setup a cron to update my `subscriptions`, which means I would need to make another `service` to keep my `subscriptions` up to date.

> But the thing is, I'm using Cloudflare Workers and there is this cruel subrequest limit of 50, so fetching the channel's upload playlists one by one is not an option as I will hit the limit sooner or later if I were to fetch many channels.

And there is this problem too when updating the `subscriptions`.

**Comment by Benjamin-Loison** [comment]
I admit I am uncomfortable as the goal of YouTube operational API is to have a working YouTube Data API v3 alternative (by keeping the same API architecture) but your request differs from this aim on two points:

1. You just want to put the workload on my API instance as you are limited by the Cloudflare Workers limit (so that's out of scope of my API)

2. The current request/answer is like this:
```
request: playlistItems?part=id&playlist=PLAYLIST_ID(&pageToken=PAGE_TOKEN)
answer:

{
    "kind": "youtube#playlistItemListResponse",
    "items": [
        {
            "kind": "youtube#playlistItem",
            "snippet": {
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": "VIDEO_0"
                }
            }
        },
        {
            "kind": "youtube#playlistItem",
            "snippet": {
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": "VIDEO_1"
                }
            }
        },
	...
        {
            "kind": "youtube#playlistItem",
            "snippet": {
                "resourceId": {
                    "kind": "youtube#video",
                    "videoId": "VIDEO_N"
                }
            }
        }
    ],
    "nextPageToken": "NEXT_PAGE_TOKEN"
}
```

and you want it to be modified in a non YouTube Data API v3 way:

```
request: playlistItems?part=id&playlist=PLAYLIST_ID_0,PLAYLIST_ID_1,...,PLAYLIST_ID_N(&pageToken=PAGE_TOKEN)
answer:


{
    "kind": "youtube#playlistListResponse",
    "items": [
        {
            "kind": "youtube#playlistItemListResponse",
            "items": [
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_0_VIDEO_0"
                    },
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_0_VIDEO_1"
                    },
                    ...
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_0_VIDEO_M"
                    }
                ]
            }
        },
        {
            "kind": "youtube#playlistItemListResponse",
            "items": [
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_1_VIDEO_0"
                    },
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_1_VIDEO_1"
                    },
                    ...
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_1_VIDEO_M"
                    }
                ]
            }
        },
	...
        {
            "kind": "youtube#playlistItemListResponse",
            "items": [
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_N_VIDEO_0"
                    },
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_N_VIDEO_1"
                    },
                    ...
                    {
                        "kind": "youtube#video",
                        "id" : "PLAYLIST_N_VIDEO_M"
                    }
                ]
            }
        },
    ],
    ("nextPageToken": "NEXT_PAGE_TOKEN")
}
```
(where the `pageToken` and `nextPageToken` would make sense only if `N = 1`)

I understand that it can help you but by doing this I think we diverge from the purpose of the API.
Sorry I sounded excited about the idea [in my first reply](https://github.com/Benjamin-Loison/YouTube-operational-API/issues/6#issuecomment-1176651409).

**Comment by Aynh** [comment]
Ok thanks for responding anyway, I didn't realize it's out of scope.. maybe I'm just too excited because this is the first time I'm ever using Youtube Data API. And sorry for keeping this issue stalled, my internet was not really stable in the past weeks.

I managed to solve my problem by not using cloudflare workers and use netlify functions instead.
