### ISSUE TITLE
`channelId` are `null` for Search: list using `hashTag` filter

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/YouTube-operational-API#88]
Reproducible URL: https://yt.lemnoslife.com/search?part=snippet&hashTag=hashtag&order=viewCount

Doing firstly #24 would help, to easily check each use case of the API.

Not urgent as can lookup the channel id from the video id using [YouTube Data API v3  Videos: list](https://developers.google.com/youtube/v3/docs/videos/list) for instance.

Reported by `499452312339873793` on [Discord](https://discord.com/channels/933841502155706418/933841503103627316/1046114769293283399).

**Comment by amastis** [comment]
It seems that the problem here is that `$channelId` is never actually instantiated 

[https://github.com/Benjamin-Loison/YouTube-operational-API/blob/8d154f9c17e99332ce817ef8722b0343554524b6/search.php#L161](https://github.com/Benjamin-Loison/YouTube-operational-API/blob/8d154f9c17e99332ce817ef8722b0343554524b6/search.php#L161)

As `$channelId` is only ever used 2 times in the entire file.
